server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/dannnii/pep3_mingeso
          search-paths: config-data2
  application:
    name: config-service
